// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "hombot adapter settings": {        "en": "LG HomBot adapter settings",                      		"de": "LG HomBot Adaptereinstellungen"},
    "onSaveAdapter": {					"en": "on save adapter restarts with new config", 				"de": "Beim Speichern der Einstellungen wird der Adapter neu gestartet."},
    "homBotURL": {                      "en": "URL (with port)",                                 		"de": "URL (mit Port)"},
    "polling": {                        "en": "Polling",                                          		"de": "Polling"},
	"pollingInterval": {                "en": "Polling interval (s)",                                       "de": "Polling Intervall (s)"}
};